### ISSUE TITLE
JS Function to generate a random String

### ISSUE THREAD

**Issue by JBraddockm** [mattpanyor/thames-trust#2]
Turn the following code into a function that would accept parameter, and return a random String for the given length.

`Math.random().toString(36).substring(2, 9)`

This code for example, returns 7 characters. 

You can read more about how this code works here: https://www.programiz.com/javascript/examples/generate-random-strings

**Comment by mattpanyor** [comment]
The code you provided was only good for 11 characters max. I used  the 'vanilla' method.
